### ISSUE TITLE
Améliorer les temps de réponses

### ISSUE THREAD

**Issue by letailli** [Bibliome/onto-relation-vizualisation#1]
Les tests effectués par Opscidia montre que même lorsque l'interface R fait des appels en parallèle, les réponses sont faites en série. Ainsi même si chaque requête ne prend que 0,3s si on a 20 requêtes il faut attendre 6s. Et c'est souvent plus.
[queries timeit.pdf](https://github.com/Bibliome/onto-relation-vizualisation/files/5518573/queries.timeit.pdf)

Charles va fournir un exemple d’appels multiples pour reproduire côté Bibliome.

2 pistes peuvent ensuite être envisagées :
- permettre les accès concurrents à la BDD
- disposer d’une nouvelle API qui permettent des listes d’objets en entrée et non plus des objets simples (Taxon -> liste de Taxons). La sortie de cette API doit permettre de faire les agrégations (donc être une liste de listes). Robert pense pouvoir mettre cette API à disposition d’Opscidia autour du 16-17 novembre.

**Comment by letailli** [comment]
@rbossy 

Voici les requêtes pour :
Concept A = Taxon
Root A = Gammaproteobacteria (ncbi:1236)
Concept B = Habitat
Root B = Food (OBT:000008)

Le diagramme s’affiche en quelques secondes ce qui ne constitue pas un cas très problématique mais cela devrait être quasi instantané si les réponses étaient renvoyées en parallèle.

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A118884&qps=FALSE&obtid=OBT%3A000038&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A118884&qps=FALSE&obtid=OBT%3A000094&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A118969&qps=FALSE&obtid=OBT%3A000038&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A118969&qps=FALSE&obtid=OBT%3A000094&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A1240482&qps=FALSE&obtid=OBT%3A000038&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A1240482&qps=FALSE&obtid=OBT%3A000094&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A135613&qps=FALSE&obtid=OBT%3A000038&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A135613&qps=FALSE&obtid=OBT%3A000094&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A135614&qps=FALSE&obtid=OBT%3A000038&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A135614&qps=FALSE&obtid=OBT%3A000094&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A135615&qps=FALSE&obtid=OBT%3A000038&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A135615&qps=FALSE&obtid=OBT%3A000094&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A135618&qps=FALSE&obtid=OBT%3A000038&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A135618&qps=FALSE&obtid=OBT%3A000094&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A135619&qps=FALSE&obtid=OBT%3A000038&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A135619&qps=FALSE&obtid=OBT%3A000094&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A135622&qps=FALSE&obtid=OBT%3A000038&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A135622&qps=FALSE&obtid=OBT%3A000094&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A135623&qps=FALSE&obtid=OBT%3A000038&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A135623&qps=FALSE&obtid=OBT%3A000094&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A135624&qps=FALSE&obtid=OBT%3A000038&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A135624&qps=FALSE&obtid=OBT%3A000094&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A135625&qps=FALSE&obtid=OBT%3A000038&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A135625&qps=FALSE&obtid=OBT%3A000094&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A1617890&qps=FALSE&obtid=OBT%3A000038&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A1617890&qps=FALSE&obtid=OBT%3A000094&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A1692040&qps=FALSE&obtid=OBT%3A000038&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A1692040&qps=FALSE&obtid=OBT%3A000094&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A1706369&qps=FALSE&obtid=OBT%3A000038&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A1706369&qps=FALSE&obtid=OBT%3A000094&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A1775403&qps=FALSE&obtid=OBT%3A000038&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A1775403&qps=FALSE&obtid=OBT%3A000094&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A1934945&qps=FALSE&obtid=OBT%3A000038&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A1934945&qps=FALSE&obtid=OBT%3A000094&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A50423&qps=FALSE&obtid=OBT%3A000038&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A50423&qps=FALSE&obtid=OBT%3A000094&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A72273&qps=FALSE&obtid=OBT%3A000038&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A72273&qps=FALSE&obtid=OBT%3A000094&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A72274&qps=FALSE&obtid=OBT%3A000038&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A72274&qps=FALSE&obtid=OBT%3A000094&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A742030&qps=FALSE&obtid=OBT%3A000038&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A742030&qps=FALSE&obtid=OBT%3A000094&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A91347&qps=FALSE&obtid=OBT%3A000038&type=habitat

http://migale.jouy.inra.fr/florilege-api/api/search/relations?taxid=ncbi%3A91347&qps=FALSE&obtid=OBT%3A000094&type=habitat

**Comment by letailli** [comment]
Toutes les requêtes (directes ou indirectes) se basent maintenant sur 1 seul appel avec des listes de concepts (gauche et droite).

Il reste 2 problèmes :
1) dans le cas des parents avec beaucoup d'enfants directs, l'appel ne passe pas "414 Request-URI Too Long"
C'est le cas pour Lactobacillus / Food (voir [INRAE Requête Lactobacillus-Food.pdf](https://github.com/Bibliome/onto-relation-vizualisation/files/5623547/INRAE.Requete.Lactobacillus-Food.pdf) )
2) la fonction ​"/search​/join-relations" ne renvoie pas de "leftroot" et "rightroot" pour rattacher les résultats aux objets en entrée. Il faudrait ajouter cela pour finir les relations indirectes (pour le moment, ça renvoie bien un résultats mais l'aggregation n'est pas bonne).

**Comment by rbossy** [comment]
J'ai tenté une optimisation du côté serveur qui aurait permis une charge moins importante. Mais c'est un échec.

Après avoir bien examiné notre architecture, je suis convaincu que la meilleure solution serait une révision de notre structure de données (en gros, on devrait pré-calculer ces relations). Mais ce n'est pas à l'ordre du jour à court terme.

On va donc devoir faire avec ce qu'on a pour l'instant et s'occuper de la réactivité plus tard.

**Comment by letailli** [comment]
Concernant le problème left-root / right-root :
La valeur demandée en entrée (à gauche) est bien renvoyée dans left-root mais celle de droite est renvoyée dans rightId au lieu de right-root.

![Capture d’écran de 2020-12-07 06-19-33](https://user-images.githubusercontent.com/2536975/101312529-44f13980-3854-11eb-90b8-7e9e085ac576.png)

basé sur cet exemple :
http://migale.jouy.inra.fr/florilege-api-dev/api/search/join-relations?left-root=OBT%3A000003&right-root=OBT%3A000004&left-type=habitat&right-type=habitat&join-type=taxon&qps=FALSE

**Comment by letailli** [comment]
Pour contourner j'ai inversé aussi dans la visualisation (rightId / rightRoot) avec un commentaire précisant le code utile si la modification est faite côté API.

**Comment by letailli** [comment]
Le bug d'inversion rightId / rightRoot est corrigé tant du côté API que du côté visualisation.

Il reste le cas des parents avec beaucoup d'enfants directs (Lactobacillus / Food par exemple qui renvoie "414 Request-URI Too Long") qui peut être réglé en passant une requête POST plutôt que GET mais il serait préférable de faire ce changement sur la future version de l'API

**Comment by rbossy** [comment]
> Le bug d'inversion rightId / rightRoot est corrigé tant du côté API que du côté visualisation.

Réparé dans l'API et l'interface synchronisée.

> Il reste le cas des parents avec beaucoup d'enfants directs (Lactobacillus / Food par exemple qui renvoie "414 Request-URI Too Long") qui peut être réglé en passant une requête POST plutôt que GET mais il serait préférable de faire ce changement sur la future version de l'API

#16
