### ISSUE TITLE
Changer les intitulés

### ISSUE THREAD

**Issue by ClaireN78** [Bibliome/onto-relation-vizualisation#10]
Titre : Je ne suis pas sure que le mot relation soit parlant pour un biologiste.

Il faudrait que le titre explicite ce qui est présenté après l'action précédente.
- Si l'action précédente est une requête et la visualisation la synthèse des réponse, je propose : your result synthesis ou result agregation ou result browsing (si on veut mettre en avant la navigation)
- Si la page est un outil indépendant, expliciter les actions possibles ? "Browsing Florilege content" ?

Concept A / Concept B : je suggère Source of the relationship / Target of the relationship

Concept ID: je propose : Enter the text here.

Afficher le nom de la relation correspondant aux types des classes sélectionnées. Ex. Lives in pour le couple Taxon - Habitat.

**Comment by letailli** [comment]
J'ai modifié les intitulés en suivant tes remarques, Claire. Ils peuvent être facilement modifiés encore via le fichier conf.ini.

J'ai notamment suivi ta recommandation pour remplacer A/B par Source/Target car je pense que c'est plus parlant mais les diagrammes sont symétriques (donc Source/Target est un peu impropre).
Du coup je n'ai pas traité la remarque qui demandait d' "afficher le nom de la relation correspondant aux types des classes sélectionnées. Ex. Lives in pour le couple Taxon - Habitat." car je pense qu'il faudrait trouver une formulation qui conservent cette symétrie. L'implémentation serait aussi un peu plus simple.

**Comment by rbossy** [comment]
Je pense que le plus clair aurait été left/right.

> Ils peuvent être facilement modifiés encore via le fichier conf.ini.

Mais ceci est le plus important, comme ça on pourra écrire nos propres labels.
