### ISSUE TITLE
Informer l'utilisateur sur le processus en cours

### ISSUE THREAD

**Issue by ClaireN78** [Bibliome/onto-relation-vizualisation#13]
Afficher un message après clic sur Process. "Process in progress", une tasse de café ? Une barre de progression ?

Peut-être afficher les éléments de la requête qui est traitée ? Peut-être permettre à l'utilisateur de l'annuler ?

**Comment by letailli** [comment]
Une barre de chargement a été ajoutée en bas à droite.
Il y a également une meilleure gestion des erreurs (qui sont affichées dans ce bloc quand elles surviennent).
