### ISSUE TITLE
Cas des trop nombreuses objets à présenter en même temps

### ISSUE THREAD

**Issue by letailli** [Bibliome/onto-relation-vizualisation#3]
C'est le sujet remonté par Claire par mail (Taxon = Lactobacillus, Habitat = Food - voir screenshot plus bas)

D'après Robert, cela ne devrait pas se poser trop souvent (la hiérarchie est là pour éviter les "râteaux"). Une manière relativement simple de résoudre ce problème est de filtrer l’affichage sur les relations au dessus d’un certain seuil (quand c'est nécessaire).

On définira donc (en config) 2 seuils :
- un seuil de nombre d’objets au dessus duquel un message indiquera que toutes les relations ne sont pas présentées
- un seuil de nombre de relations  en dessous duquel ces relations seront masqués dans ce cas.

![Screenshot_2020-11-05 Screenshot](https://user-images.githubusercontent.com/2536975/98700104-1e84cf00-2378-11eb-9c37-193b02d245c3.png)

**Comment by letailli** [comment]
Nous avons ajouté un slider qui permet (dans le cas où il y a plus de 50 objets à afficher) de piloter le seuil de la valeur d'indicateurs (relations/docs) au delà de laquelle les relations sont affichées.
Ce seuil est initialisé à la valeur médiane de l'indicateur (pour tous les objets).
![INRAE_screenshot_treshold](https://user-images.githubusercontent.com/2536975/99686051-7e1f6080-2a83-11eb-85de-e45c83bf0816.png)

Reste à faire:
- ajouter une phrase d'explication dans l'interface
- rendre le 1e seuil (50 objets) paramétrable dans la config

**Comment by letailli** [comment]
Le slider n'était pas disponible pour les représentations secondaires. C'est maintenant le cas.
Contrairement à ce qui était prévu initialement, le tableau est également soumis au même filtre car si on veut présenter les noms correspondant aux ids des concepts (ce qui est beaucoup plus lisible pour l'utilisateur), un problème de performance se pose (pour les cas où on a +10K join_id).

Il reste toujours :
- ajouter une phrase d'explication dans l'interface
- rendre le 1e seuil (50 objets) paramétrable dans la config

**Comment by letailli** [comment]
Le slider est maintenant visible.
Le seuil et le libellé d'intro (THRESHOLD à rendre plus parlant) sont dans le fichier de conf.
![Uploading inrae_joint_screenshot.png…]()

**Comment by rbossy** [comment]
@letailli
