### ISSUE TITLE
Améliorer l’UX pour mieux voir les types d’objets

### ISSUE THREAD

**Issue by letailli** [Bibliome/onto-relation-vizualisation#4]
Couleur de typage à fournir par Robert

**Comment by letailli** [comment]
Couleurs définitifs à mettre dans les fichiers conf.ini et style.css

**Comment by rbossy** [comment]
> Couleurs définitifs à mettre dans les fichiers conf.ini et style.css

C'est bien comme ça. Crois-le ou pas, mais on n'arrive pas à se mettre d'accord.
