### ISSUE TITLE
Calcul d'agrégation des jointures (dans le cas de l'indicateur "doc")

### ISSUE THREAD

**Issue by letailli** [Bibliome/onto-relation-vizualisation#5]
L'API `search/join-relations` renvoie le nombre de documents pour les relations left-join et join-right.

La présentation principale actuel n'agrége pas ces 2 listes ce qui amène à une double représentation (courbes superposées) difficile à interpréter.
Nous allons les agréger en calculant l'union de ces listes (si possible) ou la somme (sinon).

Les représentations secondaires resteront inchangées. Elles présentent le nombre de documents renvoyés par l'API pour chaque côté.

**Comment by letailli** [comment]
Pour des raisons de performance c'est la somme qui est calculée

**Comment by rbossy** [comment]
> Pour des raisons de performance c'est la somme qui est calculée

Compris. On est d'accord que c'est calculé à cette ligne:

https://github.com/Bibliome/onto-relation-vizualisation/blob/c439969d07d81b8ee6318e2aa72442408eaa28f3/inrae/global.R#L372

Dans ce cas `min` ou `max` sont envisageables.

**Comment by letailli** [comment]
Oui exactement. min et max sont envisageables et même l'union (comme évoqué plus haut) mais c'était un peu plus lourd en temps de calcul d'après mes tests.
